JI-5408 update CKEditor in wordpress (#180)
* Allow the dependency path to be overridden by child classes

This allows an implementor to choose how the library is served.

* Revert "Allow the dependency path to be overridden by child classes"

* Allow the dependency path to be overridden by child classes

This allows an implementor to choose how the library is served.

* Add Travis for all supported PHP versions

* Revert "Revert "Allow the dependency path to be overridden by child classes""

This reverts commit 87f6f3c9702993a4e653ce9178e117c576c6f35e.

* Remove incompatible code

* JI-1497 Add audio icon to H5P core font

* Change lint check to report fails correctly

* Remove type-hint from h5p.classes

* Add jQuery 3.5.1

* Add gltf to list of allowed file extensions

* Add binary variant of glTF files

glTF files can also be compressed making them smaller

* Add backwards compatibility for old libraries using jQuery's .load()

* Change fallback to original jquery .load() if first arg is not a function

* HFP-3006 Change contrast for iframe action buttons

* Add content hub and a11y changes from Drupal git

See Drupal 7 git for git history for these commits.

* Remove unused font

* Fix missing merge from Drupal git

* Reverts content hub interface change

Moved content hub changes to its own feature branch until it is ready to be implemented for all plugins

* HFP-3008 Add content language to iframe document

* HFP-3048 Add UI for getting content data

+ Update sharing UI

* HFP-3048 Add support for updating existing content

* HFP-3040 Move account registration logic into core

* Add separate trigger to trigger content sync

* Update translations and sharing UI

* Update sharing UI

* HFP-3092 Update sharing ui

* HFP-3095 Add error message if unable to contact hub

Fix translation
Update hub registration ui

* HFP-3095 Throw error if retrieving content from hub failed

* HFP-3102 Add error handling for the content hub

* HFP-3108 Adjust translations

Removed duplicate strings

* HFP-3107 Add UI strings for remove and removeImage

* HFP-3109 Update hub sharing ui

* HFP-3049 Add UI strings for cancel publish dialog

* JI-1923 Change title text of registration ui

* JI-1923 Rename 'Hub' -> 'H5P Hub'

* HFP-3120 Add UI string for content hub disciplines

* JI-1958 Add UI string needed

* Fix syntax error

* Update to latest version of registration/sharing UI

* Revert "Reverts content hub interface change"

This reverts commit 16c71b444b94d865f3742e7a48bd13015d98804b.

* Fix cleanup after reverting revert

* Fix using Core language

* Revert "Fix using Core language"

This reverts commit 4d7dccad3d42f8829ee75570100f46343a79001a.

* Update sharing UI

* Update Sharing UI

* Add support for 404 when trying to update content

* Remove token validation from Core

Causes issues for other platforms.

* Remove token validation from Core

Causes issues for other platforms.

* Update Hub Sharing + Registration clients

* JI-2081 Add translations

Move token verification to the individual integrations
Add error message to UI if logo validation fails

* Update Core font to include hub molecule icon

* HFP-3089 Update registration UI + translations

* Update hub sharing ui

* JI-2271 Add translations for the content hub

* JI-2271 Update hub sharing ui

* HFP-3232 Change placeholder text for disciplines selector

* HFP-3233 Add hub sharing ui keyword tip strings

* HFP-3234 Adjust notification text when content is shared

* Update sharing ui

* Update hub sharing ui

* JI-2366 Update sharing UI

* JI-2359 Update sharing UI

* JI-2366 Update hub sharing UI

* Update to use production content hub api

* Update hub sharing

* Update keywords description text

Fixes issue 5 from Hub review april

* Fix iframe for back button in Edge Chromium

When navigating to the previous page in Edge Chromium the H5P would often break due to it not being loaded when the page is ready. This fix will force a reload of the iframe if it is broken on initialization.

* Fix check/use of incorrect API function

This will solve fullscreen issues in Firefox

* Fix using undefined $ function

* JI-2176 Add new icons for tutorial and example links

* JI-2176 Fix incorrect paths to h5p font files

* JI-2899 Add aria label to width and height for embed popup (#110)

* HFP-3465 Fix line breaks breaking metadata field validation (#109)

* Fix linebreaks breaking metadata field validation
* HFP-3465 Use "single line" flag for regexp

* JI-2872 Fix h5p content font size in safari ios devices (#114)

* Fix double prefix when copying copy pasted content

* JI-1127 Stop import google fonts remotely
Fix #116

* JI-1127 Add License text

* Simplify code (#120)

Resize is triggered unconditionally regardless of the state of 
`H5P.isFullscreen`

* JI-3494 Add fonts to the core library (#123)

* JI-3494 Add fonts to the core library
- Added latest version of the font
- Remove unnecessary font files
- Upgrade the way it was included

* JI-3494 Make font available

* JI-3494 Fix remove unwanted inclusion of font file

* JI-3485 Include patch version in library folder name (in storage)

* JI-3485 Add support for deleting previous minor version library

* JI-3485 Fix overwriting `$new` when comparing patch versions

* Stop supporting PHP 5

* Fix Chrome fullscreen error (#113)

When embedding h5p and using the fullscreen enter/exit feature, Chrome can produce the following error:
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at HTMLDocument.<anonymous> 

This happens because arguments.callee is not accessible. To fix this, it is sufficient to name the anonymous callback function and reference it by name.

* JI-3577 Fix upgradescript for params that are null instead of undefined

* HFP-3542 Change alt text in copyright thumbnail

* HFP-3542 Give image empty alt text

* HFP-3573 Include exitButton in the tab flow

* HFP-3563 Fix Rights of Use focus and aria

* HFP-3564 Add button inside <li> for aria

* HFP-3535 H5P toolbar buttons contrast issue

* HFP-3573 Replace deprecated attribute

* HFP-3564 Change span to button

* HFP-3564 Make cursor pointer on action button

* HFP-3564 Fix indentation

* HFP-3548 Implement H5P.Tooltip (#132)

* HFP-3548 Implement H5P.Tooltip

* HFP-3548 Improve code and avoid duplication

* HFP-3548 Implement configurable position for tooltip

* HFP-3548 Add positional css to tooltip

* HFP-3548 Change tooltip on aria-label change

* HFP-3548 Add H5P.Tooltip support for Firefox

* HFP-3548 Dynamically change options.text

* HFP-3548 Remove unneccesary EventDispatcher

* HFP-3548 Prevent propogation of clicks on tooltip

* HFP-3548 Use document.body if in editor

* HFP-3548 Fix universal state bug

* HFP-3548 Remove dependency on known container

* HFP-3548 Minor fixes

* HFP-3548 Prevent overlap when adjusting

* HFP-3548 Increase z-index for tooltip

Co-authored-by: Paal Joergensen <pal.jorgensen@gmail.com>

* HFP-3584 H5P actionbar: Fix semantics + stop using title (#133)

* HFP-3548 Implement H5P.Tooltip

* HFP-3548 Improve code and avoid duplication

* HFP-3548 Implement configurable position for tooltip

* HFP-3548 Add positional css to tooltip

* HFP-3584 Add accessible tooltip to action-bar

Co-authored-by: Pål Jørgensen <pal.jorgensen@gmail.com>

* HFP-3584 Fix tooltip on actionbar

* Avoid PHP8 warning

* Remove unused parameter for libraryToString

* Improve how regexp filter works

* Fix existing library check when saving libraries

* Fixed dynamic properties deprecation in PHP 8.2 (#146)

* CH-147 Improve error messages

* JI-4911 Add support for account removed on hub

* JI-4911 Fix improved hub account removal

* Revert "JI-4911 Fix improved hub account removal"

This reverts commit b4b1df34b8d21678f8ed785bb72b1ee39697c665.

* Revert "JI-4911 Add support for account removed on hub"

This reverts commit 079191ee916c48936a8e366082f4e62c0e3d9a68.

* JI-5135 fix confirmation dialog double screen read (#151)

* Ji 5135 fix confirmation dialog double screenread (#152)

* JI-5135 fix confirmation dialog double screen read

* JI-5135 read popup header once

* JI-5135 remove unused id

* JI-5152 Allow style attributes from CKEditor 5

* JI-5152 Allow list elements to be styled (#153)

Needed for CKEditor 5

* JI-5135 revert changes (#156)

* JI-5135 revert changes

* JI-5135 tweak comment

* Add helper H5P.isEmpty

* Bump core API minor version

* JI-5366 CKEditor tables (#157)

* JI-5366 Allow styling of tables for CKEditor 5

* JI-5366 Fix styling of tables

* JI-5366 Don't purify border-width in tabels

* JI-5366 Allow bg- and border color in tables

* JI-5366 Style tables in content types like ckeditor5

* JI-5366 Allow border and vertical-align

* JI-5366 Code cleanup

* JI-5366 Change default table styling

* JI-5366 Default tables to previous styling

* JI-5366 Allow padding and height in tables

* JI-5135 fix confirmation dialog double screen read (#151)

* Ji 5135 fix confirmation dialog double screenread (#152)

* JI-5135 fix confirmation dialog double screen read

* JI-5135 read popup header once

* JI-5135 remove unused id

* JI-5135 revert changes (#156)

* JI-5135 revert changes

* JI-5135 tweak comment

* Add helper H5P.isEmpty

* Bump core API minor version

* Fixed dynamic properties deprecation in PHP 8.2 (#146)

* Fix dynamic properties deprecation warning in v8.2 (#148)

This is a continuation of the work to avoid dynamic property depreciation warnings in PHP 8.2

* Fix dynamic properties deprecation warning in v8.2 (#148)

This is a continuation of the work to avoid dynamic property depreciation warnings in PHP 8.2

* TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given (#121)

* fix: Fixed PHP8 compatibility

TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given

* fix: Fixed (TypeError) PHP8 compatibility

TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given

* JI-5430 Don't purify font family (#165)

* JI-5366 CKEditor table fixes (#163)

* JI-5366 Default to left-aligned tables

* JI-5366 Default to left-aligned table headers

* JI-5366 Actually default to left-aligned table headers

* JI-5682 add cropper translations

* JI-5366 Fix border styles of nested tables

* JI-5423 Upgrade CKE4 tables border styles (#170)

* JI-5961 fix cke5 table border bottom style (#174)

* JI-6152 add fonts to h5p core that are used by drag and drop widget (#177)

Co-authored-by: William Almnes <william.almnes@h5p.group>

* JI-6295 Fix invalid folder name in H5P export file

* JI-6286 add changes to file upload

* JI-6286 add changes to file upload

* JI-6286 Remove gltf and glb file types

* HFP-3875 Add icons for expand and collapse (#176)

* HFP-3875 Add icons for expand and collapse

* HFP-3875 Use font file provided by UX

* HFP-3875 Clean up font assets

---------

Co-authored-by: Andrew Nicols <andrew@nicols.co.uk>
Co-authored-by: Thomas <marstranderthomas@gmail.com>
Co-authored-by: Pål Jørgensen <pal.jorgensen@gmail.com>
Co-authored-by: Frode Petterson <frode.andre.petterson@gmail.com>
Co-authored-by: Oliver Tacke <o.tacke@posteo.de>
Co-authored-by: Erik Langhaug <erik.langhaug@joubel.com>
Co-authored-by: Hannaes <hanna.solstad@joubel.com>
Co-authored-by: Ravi Majithia <77275193+ravimajithia@users.noreply.github.com>
Co-authored-by: j0kerZ <joker.wartune1527@gmail.com>
Co-authored-by: Alex Kennberg <alex@kennberg.com>
Co-authored-by: Lars-Magnus Underhaug <47556433+larsmagu@users.noreply.github.com>
Co-authored-by: Zouhair Loucif <zouhair.loucif@gmail.com>
Co-authored-by: Meirza <115134930+meirzamoodle@users.noreply.github.com>
Co-authored-by: makmentins <maris.akmentins@h5p.group>
Co-authored-by: devland <5208532+devland@users.noreply.github.com>
Co-authored-by: Erik Langhaug <erik.langhaug@h5p.group>
Co-authored-by: Sagar Desai <desaisagar@users.noreply.github.com>
Co-authored-by: devland <adevland@gmail.com>
Co-authored-by: makmentins <127746763+makmentins@users.noreply.github.com>
Co-authored-by: William Almnes <william.almnes@gmail.com>
Co-authored-by: William Almnes <william.almnes@h5p.group>
Co-authored-by: Lars-Magnus Underhaug <lars-magnus.underhaug@joubel.com>